# Generated by Django 3.0.5 on 2022-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20221215_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorinfo',
            name='author_image',
            field=models.ImageField(default='default_author_image.png', upload_to='author_image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='default_book_image.png', upload_to='book_image'),
        ),
    ]
