# Generated by Django 3.2.16 on 2022-12-20 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_alter_issue_book_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='return_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 19, 13, 28, 43, 543911)),
        ),
    ]
