# Generated by Django 3.2.16 on 2022-12-20 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20221220_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_book',
            name='return_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 19, 13, 30, 58, 504378)),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
