# Generated by Django 3.2.16 on 2022-12-20 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_auto_20221220_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_book',
            name='return_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 1, 19, 13, 52, 52, 11992)),
        ),
    ]
