# Generated by Django 3.2.16 on 2022-12-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0020_remove_issue_book_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_book',
            name='is_penalty',
            field=models.BooleanField(default=True),
        ),
    ]
